### ISSUE TITLE
Minimum dependency requirements don't work/need to be updated

### ISSUE THREAD

**Issue by bendavidsteel** [lukasgebhard/Political-News-Filter#3]
I wasn't able to use the Python script with the current dependency requirements of keras>=2.3.1 and tensorflow>=2.1.0. Please see [here](https://stackoverflow.com/questions/67599535/module-tensorflow-core-compat-v2-has-no-attribute-internal) for the bug and potential solutions

Great tool otherwise, thanks for providing!

**Comment by lukasgebhard** [comment]
Thanks for the feedback! I updated the list of dependency requirements to specify exact versions rather than minimum versions. I successfully tested everything with these exact versions.
